channels:
    - conda-forge
    - defaults
    - bioconda
dependencies:
    - python=3.6
    - numpy
    - scipy
    - cython
    - matplotlib
    - seaborn
    - bokeh
    - pandas
    - h5py
    - numba
    - dask
    - cytoolz
    - ipython
    - jupyter
    - ipywidgets
    - gcc
    - parallel
    - pbgzip
    - samtools>=1.4
    - sra-tools>=2.8.1
    - fastqc
    - bwa
    - biopython
    - pyfaidx
    - pysam
    - pairix
    - pip:
        - git+https://github.com/mirnylab/pairsamtools
        - git+https://github.com/mirnylab/cooltools
        - git+https://github.com/nvictus/pybbi.git
        - git+https://github.com/nvictus/lavaburst.git
        - hg+https://bitbucket.org/mirnylab/mirnylib
        - hg+https://bitbucket.org/mirnylab/hiclib
        - bioframe
        - cooler
        - multiprocess
        - awscli
        - s3fs

